@startuml
title NUnitEngineAdapterClasses for discovery
   CanHaveFixtures <|-- TestSuite
   SuiteBase <|-- CanHaveTestCases
   SuiteBase <|-- CanHaveFixtures
   SuiteBase <|-- TestRun
   CanHaveTestCases <|-- Fixture
   SuiteBase <|-- TestCase
   CanHaveTestCases <|-- ParameterizedMethod
   CanHaveFixtures <|-- GenericFixture
   CanHaveFixtures <|-- SetUpFixture
   CanHaveTestCases <|-- Theory
   TestSuite o-- GenericFixture
   TestSuite o-- TestSuite
   Fixture o-- ParameterizedMethod
   CanHaveTestCases o-- TestCase
   CanHaveFixtures o-- Fixture
   CanHaveFixtures <|-- ParameterizedFixture
   CanHaveFixtures <|-- Assembly
   TestSuite o-- ParameterizedFixture
   TestSuite o-- SetUpFixture
   Assembly o-- TestSuite
   Assembly o-- SetUpFixture
   Fixture o-- Theory
   Fixture o-- GenericMethod
   CanHaveTestCases <|-- GenericMethod
   TestRun o-- Assembly
   SetUpFixture o-- TestSuite
   SetUpFixture o-- SetUpFixture
   SetUpFixture o-- ParameterizedFixture
   
abstract class SuiteBase {
   Property collection,
   Fixed properties
}

abstract class CanHaveTestCases {
   

}

abstract class CanHaveFixtures {
   Name:test-suite
}

class Assembly
{
   Name:test-suite
   Type:Assembly
}

class TestSuite{
   Type:TestSuite
}

class Fixture{
   Name:test-suite
   Type:TestFixture
}


   
@enduml