
name: NUnit3TestAdapter.CI

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
      with:
        dotnet-version: |
          8.0.x
    - name: Build with cake
      run: .\build.ps1 -t CI
      shell: pwsh
