
name: NUnit3TestAdapter.CI

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
      with:
        dotnet-version: |
          8.0.x
    - name: Build with cake
      run: .\build.ps1 -t CI
      shell: pwsh
