
name: NUnit3TestAdapter.CI

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        dotnet-version: |
          8.0.x
    - name: Build with cake
      run: .\build.ps1 -t CI
      shell: pwsh
